export const projects = [
  {
    title: "Datepicker Plugin",
    subtitle: "React, JavaScript, Es6, Html, css, Styled-components, Npm",
    description:
      "A flexible and custom datepicker plugin that allows users to easily select dates from a calendar interface. This plugin provides a range of features and options to tailor the datepicker to your specific needs. Also no date related third party libraries like moment.js have been used in building this application.",
    image:`${process.env.PUBLIC_URL}/datepicker.png`,
    link: "http://healthcare-labtest.netlify.app",
  },
  {
    title: "Calculator",
    subtitle: "React, JavaScript, Es6, Npm",
    description:
      "A simple yet powerful calculator built with React, designed to make calculations easy and efficient. This custom calculator app allows users to perform basic arithmetic operations such as addition, subtraction, multiplication, and division, as well as more advanced calculations like exponentiation, roots, and trigonometric functions.",
    image:`${process.env.PUBLIC_URL}/calculator.jpg`,
    link: "http://healthcare-labtest.netlify.app",
  },
  {
    title: "Healthcare Lab Tests",
    subtitle:
      "React, JavaScript, Es6, TailwindCss, React-routing, Context, Localstorage, Github, netlify",
    description:
      "Our responsive React app is designed to simplify the process of booking healthcare lab tests, making it convenient and hassle-free for patients. With a user-friendly interface and seamless navigation, you can easily search, select, and book your desired lab tests from the comfort of your own home.",
    image: `${process.env.PUBLIC_URL}/labTest.PNG`,
    link: "http://healthcare-labtest.netlify.app",
  },
];

export const skills = [
  "ReactJs",
  "Redux",
  "JavaScript",
  "TypeScript",
  "Es6 Standards",
  "NextJs",
  "Tailwind Css",
  "Css",
  "HTML",
  "Vite",
  "Webpack",
  "ESLint",
  "Prettier",
  "HighCharts",
  "Ag-Grid",
  "Axios",
  "Nginx",
  "RESTful API",
  "Postman",
  "Swagger",
  "Jest",
  "React Testing Liberary",
  "Vitest",
  "NodeJS",
  "ExpressJs",
  "PostgreSQL",
  "MySQL",
  "JWT Authentication",
  "Microservices",
  "Micro Frontend",
  "Git",
  "Github",
  "GitLab",
  "Bitbucket",
  "JIRA",
  "Confluence",
  "Agile",
];
